### ISSUE TITLE
can‘t find the facades code

### ISSUE THREAD

**Issue by MrLihj** [LorenMt/facade-urban-analysis#2]
hello，do you have the code of the paper“Local Regularity-driven City-scale Facade Detection from Aerial Images”

**Comment by lorenmt** [comment]
Hi,
No. I am not the author of that paper and thus don’t have the code to support that paper. Please contact the original authors.

On Wed, Jul 10, 2019 at 0:09, MrLihj <notifications@github.com> wrote:
hello，do you have the code of the paper“Local Regularity-driven City-scale Facade Detection from Aerial Images”

**Comment by MrLihj** [comment]
May I ask where did you get this facade detection data from? Isn't it the running code of the paper？

**Comment by lorenmt** [comment]
Yes. I was working with the same corresponding author from the paper you mentioned. But I have no access to these data now. If you need them, you still have to contact the original authors.

On Wed, Jul 10, 2019 at 0:14, MrLihj <notifications@github.com> wrote:
May I ask where did you get this facade detection data from? Isn't it the running code of the paper？

**Comment by MrLihj** [comment]
I found that your code is missing several.m files of functions in the function folder。
![image](https://user-images.githubusercontent.com/49868619/60967940-78255580-a34e-11e9-9b23-1cad8cfb12f9.png)

**Comment by MrLihj** [comment]
I found that your code is missing several.m files of functions in the function folder。
![image](https://user-images.githubusercontent.com/49868619/61107542-c0f61f00-a4b2-11e9-965f-2f8836d95e00.png)

**Comment by lorenmt** [comment]
Hi,
I am really sorry for the confusion. Since this is a rather old non-published project, I currently don't have access to those code in my local machine. If you have further help, please contact the authors of the referenced paper.
Thanks for the understand and sorry to bring any inconvenience.

On Thu, Jul 11, 2019 at 23:38, MrLihj <notifications@github.com> wrote:
I found that your code is missing several.m files of functions in the function folder。
[https://user-images.githubusercontent.com/49868619/61107542-c0f61f00-a4b2-11e9-965f-2f8836d95e00.png]
